---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: benjvi/validate-json-schemas
    tag: 20190501

inputs:
 - name: schemas
 - name: data

params:
  # path relative to schemas input
  CONTRACTS_FOLDER:
  # path relative to data input
  # defaults to file produced by terraform resource
  JSON_DATA_FILE: metadata
  SCHEMA_FILE_PATTERN: "*.json"

run:
  path: bash
  args: 
  - "-c"
  - |
    set -euo pipefail

    if [ -z "$(ls -A schemas/$CONTRACTS_FOLDER/$SCHEMA_FILE_PATTERN)" ]; then
      echo "WARNING: no schemas found"
    fi

    for contract in schemas/$CONTRACTS_FOLDER/$SCHEMA_FILE_PATTERN; do
      echo "Validating against JSON schema: $contract"
      ajv -s $contract -d data/$JSON_DATA_FILE --all-errors
    done
